[build]
builder = "NIXPACKS"
nixpacksVersion = "1.15.0"
nixpacksAppType = "node"

[deploy]
startCommand = "npm run build && npm run start"

[vars]
NODE_ENV = "production"

[[services]]
name = "telechat"
